import type { DemoScenario } from '../types/demo';

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'normal_room',
    name: 'NORMAL ROOM',
    badgeLabel: 'SCENARIO 1',
    description: 'Comfortable room (24.5°C <= 26.0°C). Motion detected. Decision engine keeps AC OFF.',
    temperature: 24.5,
    humidity: 55.0,
    motionDetected: true,
    autoMode: true,
    targetTemperature: 26,
    acMode: 'cool',
    fanSpeed: 'auto',
    initialAcPower: false,
    initialTimeSinceMotion: 0,
    expectedDecision: 'AUTO_IDLE',
    expectedAcPower: false,
    expectedReason: 'Temperature is within the configured range.',
    flowSteps: [
      { stage: 'input', label: 'DHT22 (24.5°C)', sublabel: 'Within threshold (<=26°C)', active: true },
      { stage: 'input', label: 'PIR Motion', sublabel: 'Movement detected (HIGH)', active: true },
      { stage: 'process', label: 'ESP32 CPU', sublabel: 'Evaluate Rule B', active: true },
      { stage: 'process', label: 'Decision Logic', sublabel: 'AUTO_IDLE (Standby)', active: true },
      { stage: 'output', label: 'IR Transmitter', sublabel: 'No carrier burst emitted', active: false },
      { stage: 'output', label: 'Air Conditioner', sublabel: 'Remains OFF (Energy Saved)', active: false },
    ],
  },
  {
    id: 'hot_room',
    name: 'HOT ROOM',
    badgeLabel: 'SCENARIO 2',
    description: 'Elevated temperature (29.2°C > 26.0°C) with occupancy detected. Automation triggers AC ON.',
    temperature: 29.2,
    humidity: 61.0,
    motionDetected: true,
    autoMode: true,
    targetTemperature: 26,
    acMode: 'cool',
    fanSpeed: 'auto',
    initialAcPower: false, // Transitions to true via automation
    initialTimeSinceMotion: 0,
    expectedDecision: 'AUTO_COOLING',
    expectedAcPower: true,
    expectedReason: 'Temperature is above threshold and motion is detected.',
    flowSteps: [
      { stage: 'input', label: 'DHT22 (29.2°C)', sublabel: 'Above threshold (>26°C)', active: true },
      { stage: 'input', label: 'PIR Motion', sublabel: 'Occupants present (HIGH)', active: true },
      { stage: 'process', label: 'ESP32 CPU', sublabel: 'Evaluate Rule C', active: true },
      { stage: 'process', label: 'Decision Logic', sublabel: 'AUTO_COOLING (Trigger ON)', active: true },
      { stage: 'output', label: 'IR Transmitter', sublabel: '38kHz NEC Code Transmitted', active: true },
      { stage: 'output', label: 'Air Conditioner', sublabel: 'Power ON: COOL 26°C / FAN AUTO', active: true },
    ],
  },
  {
    id: 'empty_room',
    name: 'EMPTY ROOM',
    badgeLabel: 'SCENARIO 3',
    description: 'Warm room (27.5°C > 26.0°C) vacated by occupants. Enters countdown then powers AC down.',
    temperature: 27.5,
    humidity: 58.0,
    motionDetected: false,
    autoMode: true,
    targetTemperature: 26,
    acMode: 'cool',
    fanSpeed: 'auto',
    initialAcPower: true, // Started ON while occupied
    initialTimeSinceMotion: 0, // Starts at 0s, immediately in AUTO_WAITING_FOR_TIMEOUT
    expectedDecision: 'AUTO_WAITING_FOR_TIMEOUT → AUTO_OFF_EMPTY',
    expectedAcPower: false,
    expectedReason: 'No motion detected. Waiting for the configured timeout.',
    flowSteps: [
      { stage: 'input', label: 'DHT22 (27.5°C)', sublabel: 'Above threshold (>26°C)', active: true },
      { stage: 'input', label: 'PIR Motion', sublabel: 'Room vacated (LOW)', active: true },
      { stage: 'process', label: 'ESP32 CPU', sublabel: 'Inactivity Timer Active', active: true },
      { stage: 'process', label: 'Decision Logic', sublabel: 'Waiting → AUTO_OFF_EMPTY', active: true },
      { stage: 'output', label: 'IR Transmitter', sublabel: 'Power OFF command on timeout', active: true },
      { stage: 'output', label: 'Air Conditioner', sublabel: 'Shutdown (Power OFF)', active: false },
    ],
  },
];
