/**
 * Strongly typed representation of raw sensor telemetry
 * generated by DHT22 (temperature/humidity) and PIR (motion).
 */
export interface SensorData {
  temperature: number;       // Celsius (°C)
  humidity: number;          // Relative Humidity (% RH)
  motionDetected: boolean;   // PIR motion detection (Logic HIGH/LOW)
  motion: boolean;           // Compatibility alias for existing UI components
  timestamp: number;         // Unix epoch timestamp in milliseconds
  timestampFormatted: string;// Human-readable formatted time string (HH:MM:SS)
}

/**
 * Backward-compatible interface matching existing UI consumers.
 */
export interface SensorReading extends SensorData {
  // Inherits all SensorData properties
}

export interface SensorHistoryItem {
  time: string;
  temperature: number;
  humidity: number;
  motion: boolean;
  acPower: boolean;
}
